# livro.py
import os
from model.emprestimos import Emprestimos  # Importação necessária

PASTA_ARQUIVOS = "arquivos.txt"  # Atualizado de "arquivos" para "arquivos.txt"
ARQUIVO_LIVROS = os.path.join(PASTA_ARQUIVOS, "livros.txt")

# Garantir que a pasta e o arquivo existam
os.makedirs(PASTA_ARQUIVOS, exist_ok=True)
if not os.path.exists(ARQUIVO_LIVROS):
    with open(ARQUIVO_LIVROS, "w", encoding="utf-8") as f:
        pass

class Livro:
    @staticmethod
    def listar_livros():
        """Retorna uma lista de dicionários com todos os livros disponíveis na biblioteca."""
        livros = []
        with open(ARQUIVO_LIVROS, "r", encoding="utf-8") as f:
            for linha in f:
                linha = linha.strip()
                if linha:  # Evitar linhas vazias
                    try:
                        codigo, nome, autor = linha.split(",", 2)
                        livros.append({"codigo": codigo, "nome": nome, "autor": autor})
                    except ValueError:
                        print(f"Linha mal formatada ignorada: {linha}")
        return livros

    @staticmethod
    def obter_livro(codigo):
        """Retorna as informações de um livro específico pelo código."""
        livros = Livro.listar_livros()
        for livro in livros:
            if livro["codigo"] == codigo:
                return livro
        return None

    @staticmethod
    def adicionar_livro(codigo, nome, autor):
        """Adiciona um novo livro ao arquivo, garantindo que o código e o nome sejam únicos."""
        livros = Livro.listar_livros()
        # Verificar se já existe um livro com o mesmo código ou nome
        for livro in livros:
            if livro["codigo"] == codigo:
                raise ValueError(f"Já existe um livro com o código '{codigo}'.")
            if livro["nome"].lower() == nome.lower():
                raise ValueError(f"Já existe um livro com o nome '{nome}'.")
        # Se não existir, adicionar o livro
        with open(ARQUIVO_LIVROS, "a", encoding="utf-8") as f:
            f.write(f"{codigo},{nome},{autor}\n")

    @staticmethod
    @staticmethod
    def editar_livro(codigo_atual, novo_codigo=None, novo_nome=None, novo_autor=None):
        """Edita as informações de um livro, incluindo o código."""
        livros = Livro.listar_livros()
        encontrado = False
        codigos_existentes = {livro["codigo"] for livro in livros if livro["codigo"] != codigo_atual}
        nomes_existentes = {livro["nome"].lower() for livro in livros if livro["codigo"] != codigo_atual}
        with open(ARQUIVO_LIVROS, "w", encoding="utf-8") as f:
            for livro in livros:
                if livro["codigo"] == codigo_atual:
                    encontrado = True
                    # Verificar se o novo código já existe
                    if novo_codigo:
                        if novo_codigo in codigos_existentes:
                            raise ValueError(f"Já existe um livro com o código '{novo_codigo}'.")
                        else:
                            # Atualizar o código nos empréstimos
                            Emprestimos.atualizar_codigo_livro(codigo_atual, novo_codigo)
                            livro["codigo"] = novo_codigo
                    if novo_nome:
                        if novo_nome.lower() in nomes_existentes:
                            raise ValueError(f"Já existe um livro com o nome '{novo_nome}'.")
                        livro["nome"] = novo_nome
                    if novo_autor:
                        livro["autor"] = novo_autor
                f.write(f"{livro['codigo']},{livro['nome']},{livro['autor']}\n")
        if not encontrado:
            raise ValueError(f"Nenhum livro encontrado com o código '{codigo_atual}'.")

    @staticmethod
    def remover_livro(codigo):
        """Remove um livro pelo código."""
        livros = Livro.listar_livros()
        livros_filtrados = [livro for livro in livros if livro["codigo"] != codigo]
        if len(livros) == len(livros_filtrados):
            raise ValueError(f"Nenhum livro encontrado com o código '{codigo}'.")
        with open(ARQUIVO_LIVROS, "w", encoding="utf-8") as f:
            for livro in livros_filtrados:
                f.write(f"{livro['codigo']},{livro['nome']},{livro['autor']}\n")

    @staticmethod
    def inicializar_estoque_inicial():
        """Inicializa o arquivo com os livros padrões se estiver vazio."""
        livros_iniciais = [
            "001,48 Leis do Poder,Robert Greene",
            "002,Manual de Persuasão do FBI,Jack Schafer",
            "003,As armas da persuasão: Como influenciar e não se deixar influenciar,Robert B. Cialdini",
            "004,Gatilhos Mentais: O Guia Completo com Estratégias de Negócios e Comunicações Provadas Para Você Aplicar,Allan Kardec",
            "005,Como convencer alguém em 90 segundos: Crie uma primeira impressão vendedora,Nicholas Boothman",
            "006,Pai Rico, Pai Pobre: Edição de 20 Anos Atualizada e Ampliada,Robert T. Kiyosaki",
            "007,O Homem Mais Rico da Babilônia,George S. Clason",
            "008,Os Segredos da Mente Milionária,T. Harv Eker",
            "009,Mais Esperto que o Diabo,Napoleon Hill",
            "010,O Príncipe,Nicolau Maquiavel",
            "011,A Arte da Guerra,Sun Tzu",
            "012,Como Fazer Amigos e Influenciar Pessoas,Dale Carnegie",
            "013,Meditações,Marco Aurélio",
            "014,Antifrágil: Coisas que se Beneficiam com o Caos,Nassim Nicholas Taleb",
            "015,Sapiens: Uma Breve História da Humanidade,Yuval Noah Harari",
            "016,Homo Deus: Uma Breve História do Amanhã,Yuval Noah Harari",
            "017,21 Lições para o Século 21,Yuval Noah Harari",
            "018,Thinking, Fast and Slow,Daniel Kahneman",
            "019,Factfulness: O Hábito Libertador de Só Formar Opiniões Baseadas em Fatos,Hans Rosling",
            "020,O Poder do Hábito: Por que Fazemos o que Fazemos na Vida e nos Negócios,Charles Duhigg",
            "021,Essencialismo: A Disciplinada Busca por Menos,Greg McKeown",
            "022,Atomic Habits: Hábitos Atômicos,James Clear",
            "023,Mindset: A Nova Psicologia do Sucesso,Carol S. Dweck",
            "024,Por que Dormimos: A Nova Ciência do Sono e do Sonho,Matthew Walker",
            "025,O Milagre da Manhã,Hal Elrod",
            "026,A Sutil Arte de Ligar o Fda-se,Mark Manson",
            "027,Tudo é Fda: Um Livro Sobre Esperança,Mark Manson",
            "028,Desperte Seu Gigante Interior,Tony Robbins",
            "029,Poder sem Limites,Tony Robbins",
            "030,O Poder do Agora,Eckhart Tolle",
            "031,Um Novo Mundo: O Despertar de uma Nova Consciência,Eckhart Tolle",
            "032,Você Pode Curar Sua Vida,Louise Hay",
            "033,Os Quatro Compromissos,Don Miguel Ruiz",
            "034,O Milionário Mora ao Lado,Thomas J. Stanley",
            "035,Quem Pensa Enriquece,Napoleon Hill",
            "036,O Lobo de Wall Street,Jordan Belfort",
            "037,Caixa Preta: O que a Aviação nos Ensina sobre o Sucesso,Matthew Syed",
            "038,Gigantes da Liderança,Stephen R. Covey",
            "039,Liderança: A Inteligência Emocional na Formação do Líder de Sucesso,Daniel Goleman",
            "040,Os 7 Hábitos das Pessoas Altamente Eficazes,Stephen R. Covey",
            "041,Liderança em Foco,John C. Maxwell",
            "042,O Monge e o Executivo,James C. Hunter",
            "043,Como Ser um Líder Servidor,James C. Hunter",
            "044,Liderança e Propósito: O Fator Humano como Diferencial Competitivo,Sandra Regina Miné",
            "045,A Revolta de Atlas,Ayn Rand",
            "046,A Virtude do Egoísmo,Ayn Rand",
            "047,Introdução à Epistemologia,Will Durant",
            "048,A História da Filosofia,Bertrand Russell",
            "049,Filosofia para Corajosos,Mário Sérgio Cortella",
            "050,O Livro dos Ressignificados,Mário Sérgio Cortella",
            "051,Por que Fazemos o que Fazemos,Mário Sérgio Cortella",
            "052,O Andar do Bêbado: Como o Acaso Determina Nossas Vidas,Leonard Mlodinow",
            "053,O Ponto da Virada: Como Pequenas Coisas Podem Fazer uma Grande Diferença,Malcolm Gladwell",
            "054,Fora de Série: Outliers,Malcolm Gladwell",
            "055,David e Golias: A Arte de Enfrentar Gigantes,Malcolm Gladwell",
            "056,Pequeno Manual Antirracista,Djamila Ribeiro",
            "057,Escravidão Vol. 1: Do Primeiro Leilão de Cativos em Portugal até a Morte de Zumbi dos Palmares,Laurentino Gomes",
            "058,Escravidão Vol. 2: Da Corrida do Ouro em Minas Gerais até a Chegada da Corte de Dom João ao Brasil,Laurentino Gomes",
            "059,1808,Laurentino Gomes",
            "060,1822,Laurentino Gomes",
            "061,1889,Laurentino Gomes",
            "062,O Pequeno Príncipe,Antoine de Saint-Exupéry",
            "063,Dom Casmurro,Machado de Assis",
            "064,Memórias Póstumas de Brás Cubas,Machado de Assis",
            "065,Vida e Obra de Majnun Layla,Qays ibn Al-Mulawwah",
            "066,Admirável Mundo Novo,Aldous Huxley",
            "067,1984,George Orwell",
            "068,A Revolução dos Bichos,George Orwell",
            "069,Orgulho e Preconceito,Jane Austen",
            "070,Emma,Jane Austen",
            "071,Moby Dick,Herman Melville",
            "072,Crime e Castigo,Fiódor Dostoiévski",
            "073,Os Irmãos Karamázov,Fiódor Dostoiévski",
            "074,O Idiota,Fiódor Dostoiévski",
            "075,A Metamorfose,Franz Kafka",
            "076,O Processo,Franz Kafka",
            "077,A Náusea,Jean-Paul Sartre",
            "078,O Estrangeiro,Albert Camus",
            "079,A Peste,Albert Camus",
            "080,Cem Anos de Solidão,Gabriel García Márquez",
            "081,O Amor nos Tempos do Cólera,Gabriel García Márquez",
            "082,As Veias Abertas da América Latina,Eduardo Galeano",
            "083,Na Natureza Selvagem,Jon Krakauer",
            "084,Walden,Henry David Thoreau",
            "085,As 48 Leis do Poder,Robert Greene",
            "086,A Arte da Sedução,Robert Greene",
            "087,Mestres da Estratégia,Robert Greene",
            "088,Por Trás da Cortina Vermelha,Cristiane Correa",
            "089,Sonho Grande,Cristiane Correa",
            "090,O Jeito Harvard de Ser Feliz,Shawn Achor",
            "091,O Jeito Warren Buffett de Investir,Robert G. Hagstrom",
            "092,Os Ensaios,Michel de Montaigne",
            "093,A República,Platão",
            "094,O Banquete,Platão",
            "095,Ética a Nicômaco,Aristóteles",
            "096,O Capital,Karl Marx",
            "097,Manifesto Comunista,Karl Marx",
            "098,A Origem das Espécies,Charles Darwin",
            "099,O Gene Egoísta,Richard Dawkins",
            "100,Breve História de Quase Tudo,Bill Bryson",
            "101,Cosmos,Carl Sagan",
            "102,Dragões do Éden,Carl Sagan",
            "103,O Mundo Assombrado pelos Demônios,Carl Sagan",
            "104,O Universo numa Casca de Noz,Stephen Hawking",
            "105,Breves Respostas para Grandes Questões,Stephen Hawking",
            "106,Uma Breve História do Tempo,Stephen Hawking",
            "107,O Grande Projeto,Stephen Hawking",
            "108,Fique Rico com o Mercado de Ações,William O'Neil",
            "109,O Investidor Inteligente,Benjamin Graham",
            "110,Valuation: Como Avaliar Empresas e Escolher as Melhores Ações,Aswath Damodaran",
            "111,O Encantador de Pessoas,Ken O'Donnell",
            "112,Marketing de Permissão,Seth Godin",
            "113,Tribos: Nós Precisamos Que Você Nos Lidere,Seth Godin",
            "114,Empresas Feitas para Vencer,Jim Collins",
            "115,Como as Gigantes Caem,Jim Collins",
            "116,A Startup Enxuta,Eric Ries",
            "117,Do Sonho à Realização em 4 Passos,Steve Blank",
            "118,Trabalhe 4 Horas por Semana,Timothy Ferriss",
            "119,Não me Faça Pensar,Steve Krug",
            "120,A Vaca Roxa,Seth Godin",
            "121,A Cauda Longa,Chris Anderson",
            "122,Como Ser F***,Caio Carneiro",
            "123,Seja F***!,Caio Carneiro",
            "124,O Livro Negro do Empreendedor,Fernando Trias de Bes",
            "125,Empreendedorismo para Subversivos,Rafael B. Carvalho",
            "126,O Estilo Bezos de Gerenciar,Steve Anderson",
            "127,Os Segredos do Vale do Silício,John Doerr",
            "128,Liderança com Propósito,Rick Warren",
            "129,Feitas para Durar,Jim Collins",
            "130,O Efeito Halo,Phil Rosenzweig",
            "131,Os Grandes Mestres do Marketing,Pierre Loewe",
            "132,Gestão da Emoção,Augusto Cury",
            "133,O Código da Inteligência,Augusto Cury",
            "134,Ansiedade: Como Enfrentar o Mal do Século,Augusto Cury",
            "135,12 Regras para a Vida: Um Antídoto para o Caos,Jordan B. Peterson",
            "136,A Coragem de Não Agradar,Ichiro Kishimi",
            "137,Ikigai: Os Segredos dos Japoneses para uma Vida Longa e Feliz,Héctor García",
            "138,Fluir: A Psicologia da Felicidade,Mihaly Csikszentmihalyi",
            "139,Resiliência: A Arte de Superar Desafios,Steven Southwick",
            "140,O Ponto de Equilíbrio,Chip Heath",
            "141,A Psicologia Financeira,Morgan Housel",
            "142,Um Psicólogo no Campo de Concentração,Viktor Frankl",
            "143,O Homem em Busca de um Sentido,Viktor Frankl",
            "144,Os Segredos da Mente Jovem,Augusto Cury",
            "145,A Terceira Alternativa,Stephen R. Covey",
            "146,Liderança de Alta Performance,Brendon Burchard",
            "147,O Poder da Autoresponsabilidade,Paulo Vieira",
            "148,O Poder da Ação,Paulo Vieira",
            "149,Plano de Ação,Paulo Vieira",
            "150,Criatividade S.A.,Ed Catmull",
            "151,O Jeito Disney de Encantar Clientes,Disney Institute",
            "152,O Jeito Harvard de Negociar,Bruce Patton",
            "153,Como Negociar Como um Bilionário,Christopher Voss",
            "154,A Estratégia do Oceano Azul,Chan Kim",
            "155,O Livro do Perdão,Desmond Tutu",
            "156,A Inteligência Emocional,Daniel Goleman",
            "157,Foco: A Atenção e Seu Papel Fundamental para o Sucesso,Daniel Goleman",
            "158,O Poder do Subconsciente,Joseph Murphy",
            "159,A Lei do Triunfo,Napoleon Hill",
            "160,Como Se Tornar Inabalável,Tony Robbins",
            "161,O Poder da Intenção,Wayne Dyer",
            "162,Milagres Acontecem,Brian Weiss",
            "163,Sempre em Frente,Joe De Sena",
            "164,Nunca Desista,Nick Vujicic",
            "165,Seja Firme!,Amy Morin",
            "166,Inteligência Positiva,Shirzad Chamine",
            "167,Para Além do Bem e do Mal,Friedrich Nietzsche",
            "168,Assim Falava Zaratustra,Friedrich Nietzsche",
            "169,O Anticristo,Friedrich Nietzsche",
            "170,A Riqueza das Nações,Adam Smith",
            "171,Política,Aristóteles",
            "172,Metafísica,Aristóteles",
            "173,A Democracia na América,Alexis de Tocqueville",
            "174,A Teoria Geral do Emprego, do Juro e da Moeda,John Maynard Keynes",
            "175,O Espírito das Leis,Montesquieu",
            "176,A Arte de Escrever,Arthur Schopenhauer",
            "177,A Filosofia como Modo de Vida,Pierre Hadot",
            "178,Amor Líquido,Zygmunt Bauman",
            "179,Modernidade Líquida,Zygmunt Bauman",
            "180,Capitalismo e Liberdade,Milton Friedman",
            "181,Anatomia do Estado,Murray Rothbard",
            "182,A Ética Protestante e o Espírito do Capitalismo,Max Weber",
            "183,O Mundo de Sofia,Jostein Gaarder",
            "184,O Pêndulo de Foucault,Umberto Eco",
            "185,O Nome da Rosa,Umberto Eco",
            "186,As Intermitências da Morte,José Saramago",
            "187,Ensaio Sobre a Cegueira,José Saramago",
            "188,O Livro das Virtudes,William Bennett",
            "189,O Livro da Filosofia,DK Publishing",
            "190,O Livro da Ciência,DK Publishing",
            "191,Jogos Vorazes,Suzanne Collins",
            "192,A Esperança,Suzanne Collins",
            "193,Em Chamas,Suzanne Collins",
            "194,Duna,Frank Herbert",
            "195,Fundação,Isaac Asimov",
            "196,Eu, Robô,Isaac Asimov",
            "197,Neuromancer,William Gibson",
            "198,O Código Da Vinci,Dan Brown",
            "199,Inferno,Dan Brown",
            "200,Anjos e Demônios,Dan Brown",
            "201,Fortaleza Digital,Dan Brown",
            "202,Ponto de Impacto,Dan Brown",
            "203,O Silmarillion,J.R.R. Tolkien",
            "204,O Hobbit,J.R.R. Tolkien",
            "205,Senhor dos Anéis: A Sociedade do Anel,J.R.R. Tolkien",
            "206,Senhor dos Anéis: As Duas Torres,J.R.R. Tolkien",
            "207,Senhor dos Anéis: O Retorno do Rei,J.R.R. Tolkien",
            "208,Game of Thrones: A Guerra dos Tronos,George R.R. Martin",
            "209,Game of Thrones: A Fúria dos Reis,George R.R. Martin",
            "210,Game of Thrones: A Tormenta de Espadas,George R.R. Martin",
            "211,A Dança dos Dragões,George R.R. Martin",
            "212,Os Ventos do Inverno,George R.R. Martin",
            "213,Fire & Blood: A História dos Targaryen,George R.R. Martin",
            "214,Harry Potter e a Pedra Filosofal,J.K. Rowling",
            "215,Harry Potter e a Câmara Secreta,J.K. Rowling",
            "216,Harry Potter e o Prisioneiro de Azkaban,J.K. Rowling",
            "217,Harry Potter e o Cálice de Fogo,J.K. Rowling",
            "218,Harry Potter e a Ordem da Fênix,J.K. Rowling",
            "219,Harry Potter e o Enigma do Príncipe,J.K. Rowling",
            "220,Harry Potter e as Relíquias da Morte,J.K. Rowling",
            "221,O Chamado de Cthulhu,H.P. Lovecraft",
            "222,Na Montanha da Loucura,H.P. Lovecraft",
            "223,A Cor que Caiu do Espaço,H.P. Lovecraft",
            "224,O Exorcista,William Peter Blatty",
            "225,Drácula,Bram Stoker",
            "226,Frankenstein,Mary Shelley",
            "227,Entrevista com o Vampiro,Anne Rice",
            "228,O Mundo Perdido,Arthur Conan Doyle",
            "229,Os Miseráveis,Victor Hugo",
            "230,O Corcunda de Notre Dame,Victor Hugo",
            "231,Guerra e Paz,Leon Tolstói",
            "232,Anna Kariênina,Leon Tolstói",
            "233,A Divina Comédia,Dante Alighieri",
            "234,Ilíada,Homero",
            "235,Odisseia,Homero",
            "236,Os Três Mosqueteiros,Alexandre Dumas",
            "237,O Conde de Monte Cristo,Alexandre Dumas",
            "238,Madame Bovary,Gustave Flaubert",
            "239,O Retrato de Dorian Gray,Oscar Wilde",
            "240,Canções de Inocência e de Experiência,William Blake",
            "241,Fedro,Platão",
            "242,O Capital no Século XXI,Thomas Piketty",
            "243,A Sociedade do Cansaço,Byung-Chul Han",
            "244,No Enxame: Perspectivas do Digital,Byung-Chul Han",
            "245,Panfleto Contra o Trabalho,Grupo Krisis",
            "246,A Vida Que Vale a Pena Ser Vivida,Clóvis de Barros Filho",
            "247,O Que É Filosofia?,Gilles Deleuze",
            "248,O Anti-Édipo,Gilles Deleuze",
            "249,Moral e Ética,Mário Sérgio Cortella",
            "250,A Vida dos Doze Césares,Suetônio",
            "251,A República de Platão,Alain Badiou",
            "252,O Senhor das Moscas,William Golding",
            "253,1984,George Orwell",
            "254,A Revolução dos Bichos,George Orwell",
            "255,A Máquina do Tempo,H.G. Wells",
            "256,O Homem Invisível,H.G. Wells",
            "257,Guerra dos Mundos,H.G. Wells",
            "258,Contos Completos,Edgar Allan Poe",
            "259,O Corvo,Edgar Allan Poe",
            "260,O Coração Delator,Edgar Allan Poe",
            "261,Morte no Nilo,Agatha Christie",
            "262,Assassinato no Expresso Oriente,Agatha Christie",
            "263,Os Crimes ABC,Agatha Christie",
            "264,E Não Sobrou Nenhum,Agatha Christie",
            "265,Dom Quixote,Miguel de Cervantes",
            "266,A Morte de Ivan Ilitch,Leon Tolstói",
            "267,Noites Brancas,Fiódor Dostoiévski",
            "268,Memórias do Subsolo,Fiódor Dostoiévski",
            "269,Laranja Mecânica,Anthony Burgess",
            "270,O Apanhador no Campo de Centeio,J.D. Salinger",
            "271,O Sol é para Todos,Harper Lee",
            "272,Admirável Mundo Novo,Aldous Huxley",
            "273,Os Filhos de Húrin,J.R.R. Tolkien",
            "274,O Aleph,Jorge Luis Borges",
            "275,Ficciones,Jorge Luis Borges",
            "276,O Livro dos Seres Imaginários,Jorge Luis Borges",
            "277,Cem Anos de Solidão,Gabriel García Márquez",
            "278,Crônica de uma Morte Anunciada,Gabriel García Márquez",
            "279,A Casa dos Espíritos,Isabel Allende",
            "280,Do Amor e Outros Demônios,Gabriel García Márquez",
            "281,A Montanha Mágica,Thomas Mann",
            "282,O Lobo da Estepe,Hermann Hesse",
            "283,Sidarta,Hermann Hesse",
            "284,Demian,Hermann Hesse",
            "285,As Ondas,Virginia Woolf",
            "286,Orlando: Uma Biografia,Virginia Woolf",
            "287,Entre os Atos,Virginia Woolf",
            "288,To the Lighthouse,Virginia Woolf",
            "289,Mrs. Dalloway,Virginia Woolf",
            "290,Jane Eyre,Charlotte Brontë",
            "291,O Morro dos Ventos Uivantes,Emily Brontë",
            "292,Lolita,Vladimir Nabokov",
            "293,A História Sem Fim,Michael Ende",
            "294,As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa,C.S. Lewis",
            "295,As Crônicas de Nárnia: O Príncipe Caspian,C.S. Lewis",
            "296,As Crônicas de Nárnia: A Viagem do Peregrino da Alvorada,C.S. Lewis",
            "297,As Crônicas de Nárnia: A Cadeira de Prata,C.S. Lewis",
            "298,As Crônicas de Nárnia: O Cavalo e Seu Menino,C.S. Lewis",
            "299,As Crônicas de Nárnia: O Sobrinho do Mago,C.S. Lewis",
            "300,As Crônicas de Nárnia: A Última Batalha,C.S. Lewis",
            "301,O Jardim Secreto,Frances Hodgson Burnett",
            "302,Pollyanna,Eleanor H. Porter",
            "303,As Aventuras de Tom Sawyer,Mark Twain",
            "304,As Aventuras de Huckleberry Finn,Mark Twain",
            "305,Morte e Vida Severina,João Cabral de Melo Neto",
            "306,Vidas Secas,Graciliano Ramos",
            "307,Grande Sertão: Veredas,João Guimarães Rosa",
            "308,Capitães da Areia,Jorge Amado",
            "309,Dona Flor e Seus Dois Maridos,Jorge Amado",
            "310,Tieta do Agreste,Jorge Amado",
            "311,O Pagador de Promessas,Dias Gomes",
            "312,São Bernardo,Graciliano Ramos",
            "313,Memorial de Aires,Machado de Assis",
            "314,Quincas Borba,Machado de Assis",
            "315,Iracema,José de Alencar",
            "316,O Guarani,José de Alencar",
            "317,Luciola,José de Alencar",
            "318,A Moreninha,Joaquim Manuel de Macedo",
            "319,Senhora,José de Alencar",
            "320,Auto da Compadecida,Ariano Suassuna",
            "321,Macunaíma,Mário de Andrade",
            "322,Os Sertões,Euclides da Cunha",
            "323,Triste Fim de Policarpo Quaresma,Lima Barreto",
            "324,O Ateneu,Raul Pompeia",
            "325,Poemas Escolhidos,Carlos Drummond de Andrade",
            "326,Poesia Completa,Manuel Bandeira",
            "327,O Tempo e o Vento,Érico Veríssimo",
            "328,Incidente em Antares,Érico Veríssimo",
            "329,Amar, Verbo Intransitivo,Mário de Andrade",
            "330,Serafim Ponte Grande,Oswald de Andrade",
            "331,Misticismo e Filosofia,Huberto Rohden",
            "332,A Cabana,William P. Young",
            "333,Querido John,Nicholas Sparks",
            "334,A Culpa é das Estrelas,John Green",
            "335,Cidades de Papel,John Green",
            "336,Quem é Você, Alasca?,John Green",
            "337,O Teorema Katherine,John Green",
            "338,Extraordinário,R.J. Palacio",
            "339,Se Eu Ficar,Gayle Forman",
            "340,A Garota no Trem,Paula Hawkins",
            "341,A Mulher na Janela,A.J. Finn",
            "342,O Homem de Giz,C.J. Tudor",
            "343,A Paciente Silenciosa,Alex Michaelides",
            "344,Verity,Colleen Hoover",
            "345,É Assim que Acaba,Colleen Hoover",
            "346,Confesse,Colleen Hoover",
            "347,Tarde Demais,Colleen Hoover",
            "348,Pessoas Normais,Sally Rooney",
            "349,Uma Vida Pequena,Hanya Yanagihara",
            "350,Daisy Jones & The Six,Taylor Jenkins Reid",
            "351,Malibu Renasce,Taylor Jenkins Reid",
            "352,Os Sete Maridos de Evelyn Hugo,Taylor Jenkins Reid",
            "353,Um Lugar Bem Longe Daqui,Delia Owens",
            "354,A Balada de Songbirds and Snakes,Suzanne Collins",
            "355,Shadow and Bone,Leigh Bardugo",
            "356,Siege and Storm,Leigh Bardugo",
            "357,Ruin and Rising,Leigh Bardugo",
            "358,Six of Crows,Leigh Bardugo",
            "359,Crooked Kingdom,Leigh Bardugo",
            "360,King of Scars,Leigh Bardugo",
            "361,Rule of Wolves,Leigh Bardugo",
            "362,O Nome do Vento,Patrick Rothfuss",
            "363,O Temor do Sábio,Patrick Rothfuss",
            "364,A Música do Silêncio,Patrick Rothfuss",
            "365,O Ciclo da Herança: Eragon,Christopher Paolini",
            "366,O Ciclo da Herança: Eldest,Christopher Paolini",
            "367,O Ciclo da Herança: Brisingr,Christopher Paolini",
            "368,O Ciclo da Herança: Herança,Christopher Paolini",
            "369,O Assassinato de Roger Ackroyd,Agatha Christie",
            "370,O Caso dos Dez Negrinhos,Agatha Christie",
            "371,Um Corpo na Biblioteca,Agatha Christie",
            "372,M ou N?,Agatha Christie",
            "373,O Cavalo Amarelo,Agatha Christie",
            "374,Caixa de Pássaros,Josh Malerman",
            "375,Insônia,Stephen King",
            "376,A Coisa,Stephen King",
            "377,O Iluminado,Stephen King",
            "378,Doutor Sono,Stephen King",
            "379,IT: A Coisa,Stephen King",
            "380,Christine,Stephen King",
            "381,Joyland,Stephen King",
            "382,Carrie,Stephen King",
            "383,A Espera de um Milagre,Stephen King",
            "384,Sob a Redoma,Stephen King",
            "385,O Bazar dos Sonhos Ruins,Stephen King",
            "386,Os Sete,André Vianco",
            "387,Sementes no Gelo,André Vianco",
            "388,O Turno da Noite,André Vianco",
            "389,A Casa,André Vianco",
            "390,Vampiro-Rei,André Vianco",
            "391,O Código dos Justos,Leonardo Torres",
            "392,Proibido,Tabitha Suzuma",
            "393,Para Todos os Garotos que Já Amei,Jenny Han",
            "394,P.S. Ainda Amo Você,Jenny Han",
            "395,Agora e Para Sempre,Jenny Han",
            "396,A Seleção,Kiera Cass",
            "397,A Elite,Kiera Cass",
            "398,A Escolha,Kiera Cass",
            "399,A Herdeira,Kiera Cass",
            "400,A Coroa,Kiera Cass",
            "401,Os Bridgertons: O Duque e Eu,Julia Quinn",
            "402,Os Bridgertons: O Visconde que Me Amava,Julia Quinn",
            "403,Os Bridgertons: Um Perfeito Cavalheiro,Julia Quinn",
            "404,Os Bridgertons: Os Segredos de Colin Bridgerton,Julia Quinn",
            "405,Os Bridgertons: Para Sir Phillip, com Amor,Julia Quinn",
            "406,Os Bridgertons: O Conde Enfeitiçado,Julia Quinn",
            "407,Os Bridgertons: Um Beijo Inesquecível,Julia Quinn",
            "408,Os Bridgertons: A Caminho do Altar,Julia Quinn",
            "409,Os Bridgertons: E Viveram Felizes Para Sempre,Julia Quinn",
            "410,Corte de Espinhos e Rosas,Sarah J. Maas",
            "411,Corte de Névoa e Fúria,Sarah J. Maas",
            "412,Corte de Asas e Ruína,Sarah J. Maas",
            "413,Corte de Gelo e Estrelas,Sarah J. Maas",
            "414,Corte de Chamas Prateadas,Sarah J. Maas",
            "415,Trono de Vidro,Sarah J. Maas",
            "416,Coroa da Meia-Noite,Sarah J. Maas",
            "417,Herdeira do Fogo,Sarah J. Maas",
            "418,Rainha das Sombras,Sarah J. Maas",
            "419,Império de Tempestades,Sarah J. Maas",
            "420,Torre do Alvorecer,Sarah J. Maas",
            "421,Reino de Cinzas,Sarah J. Maas",
            "422,Cidade da Lua Crescente: Casa de Terra e Sangue,Sarah J. Maas",
            "423,Cidade da Lua Crescente: Casa de Céu e Respiração,Sarah J. Maas",
            "424,O Pistoleiro,Stephen King",
            "425,A Escolha dos Três,Stephen King",
            "426,As Terras Devastadas,Stephen King",
            "427,Mago: Aprendiz,Raymond E. Feist",
            "428,Mago: Mestre,Raymond E. Feist",
            "429,Império: Filha do Império,Raymond E. Feist",
            "430,Império: Senhor do Império,Raymond E. Feist",
            "431,A Batalha do Apocalipse,Eduardo Spohr",
            "432,Filhos do Éden: Herdeiros de Atlântida,Eduardo Spohr",
            "433,Filhos do Éden: Anjos da Morte,Eduardo Spohr",
            "434,Filhos do Éden: Paraíso Perdido,Eduardo Spohr",
            "435,A Caverna do Dragão,Alexandre Callari",
            "436,A Era dos Mortos,Rodrigo de Oliveira",
            "437,O Vale dos Mortos,Rodrigo de Oliveira",
            "438,A Senhora do Lago,Andrzej Sapkowski",
            "439,Tempo de Desprezo,Andrzej Sapkowski",
            "440,Espada do Destino,Andrzej Sapkowski",
            "441,A Torre da Andorinha,Andrzej Sapkowski",
            "442,Batismo de Fogo,Andrzej Sapkowski",
            "443,O Sangue dos Elfos,Andrzej Sapkowski",
            "444,A Maldição do Corvo,Andrzej Sapkowski",
            "445,Crônicas Saxônicas: O Último Reino,Bernard Cornwell",
            "446,Crônicas Saxônicas: O Cavaleiro da Morte,Bernard Cornwell",
            "447,Crônicas Saxônicas: Os Senhores do Norte,Bernard Cornwell",
            "448,Crônicas Saxônicas: A Canção da Espada,Bernard Cornwell",
            "449,Crônicas Saxônicas: Terra em Chamas,Bernard Cornwell",
            "450,O Arqueiro,Bernard Cornwell",
            "451,O Andarilho,Bernard Cornwell",
            "452,O Herege,Bernard Cornwell",
            "453,As Crônicas de Artur: O Rei do Inverno,Bernard Cornwell",
            "454,As Crônicas de Artur: O Inimigo de Deus,Bernard Cornwell",
            "455,As Crônicas de Artur: Excalibur,Bernard Cornwell",
            "456,A Trilogia da Fundação: Fundação,Isaac Asimov",
            "457,A Trilogia da Fundação: Fundação e Império,Isaac Asimov",
            "458,A Trilogia da Fundação: Segunda Fundação,Isaac Asimov",
            "459,O Jardim de Cemento,Ian McEwan",
            "460,Reparação,Ian McEwan",
            "461,Na Praia,Ian McEwan",
            "462,Amsterdam,Ian McEwan",
            "463,A Casa Torta,Agatha Christie",
            "464,Convite para um Homicídio,Agatha Christie",
            "465,Depois do Funeral,Agatha Christie",
            "466,O Misterioso Caso de Styles,Agatha Christie",
            "467,Assassinato na Casa do Pastor,Agatha Christie",
            "468,As Bruxas de Salem,Arthur Miller",
            "469,A Letra Escarlate,Nathaniel Hawthorne",
            "470,O Grande Gatsby,F. Scott Fitzgerald",
            "471,Este Lado do Paraíso,F. Scott Fitzgerald",
            "472,Suave é a Noite,F. Scott Fitzgerald",
            "473,O Dia do Chacal,Frederick Forsyth",
            "474,O Quinto Cavaleiro,Larry Collins",
            "475,Coma,Robin Cook",
            "476,A Identidade Bourne,Robert Ludlum",
            "477,O Legado Bourne,Eric Van Lustbader",
            "478,A Profecia,David Seltzer",
            "479,O Menino do Pijama Listrado,John Boyne",
            "480,Deixe a Neve Cair,John Green",
            "481,Uma Longa Jornada,Nicholas Sparks",
            "482,A Escolha,Nicholas Sparks",
            "483,O Diário de uma Paixão,Nicholas Sparks",
            "484,Uma Carta de Amor,Nicholas Sparks",
            "485,O Resgate,Nicholas Sparks",
            "486,Um Porto Seguro,Nicholas Sparks",
            "487,Um Amor para Recordar,Nicholas Sparks",
            "488,O Guardião,Nicholas Sparks",
            "489,Três Metros Acima do Céu,Federico Moccia",
            "490,Desculpa se te Chamo de Amor,Federico Moccia",
            "491,Desculpa, Quero Me Casar Contigo,Federico Moccia",
            "492,Marley & Eu,John Grogan",
            "493,Comer, Rezar, Amar,Elizabeth Gilbert",
            "494,A Última Música,Nicholas Sparks",
            "495,O Melhor de Mim,Nicholas Sparks",
            "496,A Casa das Sete Mulheres,Letícia Wierzchowski",
            "497,O Tempo Entre Costuras,María Dueñas",
            "498,As Cores da Vida,Kristin Hannah",
            "499,O Rouxinol,Kristin Hannah",
            "500,Quando a Noite Cai,Carina Rissi",
        ]
        # Verifica se o arquivo está vazio ou não existe
        if not os.path.exists(ARQUIVO_LIVROS) or os.stat(ARQUIVO_LIVROS).st_size == 0:
            with open(ARQUIVO_LIVROS, "w", encoding="utf-8") as f:
                f.write("\n".join(livros_iniciais) + "\n")

# Chamar o método para inicializar o estoque inicial após a definição da classe
Livro.inicializar_estoque_inicial()
